import { Product } from '../../types/products.type';

export const products: Product[] = [
  {
    id: 1,
    product_name: 'Jacket',
    product_img: 'shop-1',
    price: 30,
    ratings: 4,
    product_description: '',
    category_id: 2,
  },
  {
    id: 2,
    product_name: 'Purse',
    product_img: 'shop-2',
    price: 40,
    ratings: 3,
    product_description: '',
    category_id: 2,
  },
  {
    id: 3,
    product_name: 'frock',
    product_img: 'shop-3',
    price: 50,
    ratings: 2,
    product_description: '',
    category_id: 2,
  },
  {
    id: 4,
    product_name: 'Denim Pant',
    product_img: 'shop-4',
    price: 60,
    ratings: 5,
    product_description: '',
    category_id: 2,
  },
  {
    id: 5,
    product_name: 'Laced Boots',
    product_img: 'shop-5',
    price: 70,
    ratings: 5,
    product_description: '',
    category_id: 2,
  },
  {
    id: 6,
    product_name: 'Back pack',
    product_img: 'shop-6',
    price: 80,
    ratings: 4,
    product_description: '',
    category_id: 1,
  },
  {
    id: 7,
    product_name: 'Ear Rings',
    product_img: 'shop-7',
    price: 90,
    ratings: 3,
    product_description: '',
    category_id: 2,
  },
  {
    id: 8,
    product_name: 'Rubber band',
    product_img: 'shop-8',
    price: 100,
    ratings: 4.5,
    product_description: '',
    category_id: 2,
  },
  {
    id: 9,
    product_name: 'Black Boots',
    product_img: 'shop-9',
    price: 100,
    ratings: 3.5,
    product_description: '',
    category_id: 2,
  },
];
